myblog/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.PostView.as_view(), name='Post'),
    path('<int:pk>/', views.PostDetail.as_view()),
    path('review/<int:pk>/', views.AddComments.as_view(), name='add_comments'),
    path('<int:pk>/add_likes/', views.AddLike.as_view(), name='add_likes'),
    path('<int:pk>/del_likes/', views.DelLike.as_view(), name='del_likes'),
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/blog/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField('Заголовок',max_length=200)
    description = models.TextField('Текст')
    author = models.CharField('Имя автора', max_length=100)
    date = models.DateField('Дата публикации')
    img = models.ImageField('изображение', upload_to='image/%Y')

    def __str__(self):
        return f'{self.title}, {self.author}'

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'


class Comments(models.Model):
    '''Комментарии'''
    email = models.EmailField()
    name = models.CharField('Имя', max_length=200)
    text_comments = models.TextField('Текст комментария', max_length=2000)
    post = models.ForeignKey(Post, verbose_name='Публикация', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}, {self.post}'

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Likes(models.Model):
    '''Лайки'''
    ip = models.CharField('Адрес',max_length=100)
    pos = models.ForeignKey(Post, verbose_name='Публикация', on_delete=models.CASCADE)

myblog/blog/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from .models import Post, Likes
from .form import CommentsForm


class PostView(View):
    '''Вывод записей'''
    def get(self, request):
        posts = Post.objects.all()
        return render(request, 'blog/index.html', {'post_list': posts})


class PostDetail(View):
    '''Детали всего'''
    def get(self, request, pk):
        post = Post.objects.get(id=pk)
        return render(request, 'blog/blog_detail.html', {'post': post})


class AddComments(View):
    '''Реализация отправки сообщений'''
    def post(self, request, pk):
        form = CommentsForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.post_id = pk
            form.save()
        return redirect(f'/{pk}')


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


class AddLike(View):
    def get(self, request, pk):
        ip_client = get_client_ip(request)
        try:
            Likes.objects.get(ip=ip_client, pos_id=pk)
            return redirect(f'/{pk}')
        except:
            new_like = Likes()
            new_like.ip = ip_client
            new_like.pos_id = int(pk)
            new_like.save()
            return redirect(f'/{pk}')


class DelLike(View):
    def get(self, request, pk):
        ip_client = get_client_ip(request)
        try:
            lik = Likes.objects.get(ip=ip_client)
            lik.delete()
            return redirect(f'/{pk}')
        except:
            return redirect(f'/{pk}')

myblog/templates/blog/blog_detail.html
{% load static %}
<html >
<head>
	<title>Мой блог</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />

	<link rel="shortcut icon" href="css/images/favicon.ico" />

</head>
<body>
<div class="shell">
	<div class="border">

		<div id="navigation">
			<ul>
			    <li><a href="/" class="active">Главная</a></li>
			    <li><a href="/admin">Админ панель</a></li>

			</ul>
		</div>

		<div id="main">
			<div id="content" class="left">

				<div class="projects">
					<h3>{{ post.title }}</h3>
                    <p align="center">
                        <img src="{{ post.img.url }}" alt="Картинка" width="50%" />
                    </p>
					<div class="item">
						<div class="text left">
							<p>{{ post.description }}</p>
							<p>Автор:  {{ post.author }}</p>
						</div>
						<div class="cl">&nbsp;</div>
					</div>
				</div>
			</div>

				<div>
					<br>
					<p>Понравилось: {{ post.likes_set.all.count }}</p>
					<br>
					<a href="{% url 'add_likes' post.id %}">Понравилось</a>
					<a href="{% url 'del_likes' post.id %}">Не понравилось</a>
				</div>

				<div class="form-comment">
					<h3>Оставить комментарий</h3>
					<div>
						<form action="{% url 'add_comments' post.id %}" method="post">
							{% csrf_token %}
									<div>
										<label>Ваш комментарий</label>
										<textarea name="text_comments"></textarea>
									</div>

											<div>
												<label>Ваше имя *</label>
												<input type="text" name="name">
											</div>

													<div>
														<label>Ваша email</label>
														<input type="email" name="email">
													</div>

															<div>
																<input type="submit">
															</div>
						</form>
					</div>
				</div>
			<div class="cl">&nbsp;</div>
		</div>
		{% for comment in post.comments_set.all %}
		<div class="view-comment">
			<h4>{{ comment.name }}</h4>

			<p>
				{{ comment.text_comments }}
			</p>
		</div>

		{% endfor %}

	</div>

	<div id="footer">
		<p class="copy right">Copyright &copy;  2022 </p>
	</div>
</div>
</body>
</html>

myblog/templates/blog/index.html
{% load static %}
<html >
<head>
	<title>Мой блог</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />

	<link rel="shortcut icon" href="css/images/favicon.ico" />

</head>
<body>
<div class="shell">
	<div class="border">

		<div id="navigation">
			<ul>
			    <li><a href="/" class="active">Главная</a></li>
			    <li><a href="/admin">Админ панель</a></li>
			    
			</ul>
		</div>

		<div id="main">
			<div id="content" class="left">
				
				<div class="projects">
					<h3>Записи</h3>
					{% for post in post_list %}
					<div class="item">
						<div class="image left">
							<a href="#"><img src="{{ post.img.url }}" alt="Картинка" width="200px" /></a>
						</div>
						<div class="text left">
							<h4><a href="{{ post.id }}">{{ post.title }}</a></h4>
							<p>{{ post.description }}</p>
							<p>Автор:  {{ post.author }}</p>
						</div>
						<div class="cl">&nbsp;</div>
					</div>
					{% endfor %}
				</div>
			</div>
			
			<div class="cl">&nbsp;</div>
		</div>
		

	</div>
	
	<div id="footer">
		<p class="copy right">Copyright &copy;  2022 </p>
	</div>
</div>
</body>
</html>